on:
    workflow_dispatch: 
        inputs:
            myInput:
                type: string
                description: "this string will be printed"
                required: true
                default: "upload package and deploy "


jobs:
    replace-artifact-version:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - name: Set up JDK 11
          uses: actions/setup-java@v4 
          with:
             java-version: '17'
             distribution: 'temurin'
             cache: maven
        - name: Build and upload with Maven
          run: echo "sudhir printed"

        - name: Install xmlstarlet
          run: sudo apt-get install -y xmlstarlet  

        - name: replace artifact version
          run: |
            #sed -i 's/<version>.*<\/version>/<version>new_version<\/version>/' pom.xml
            xmlstarlet ed -L -u "/project/version" -v "2.0.0-SNAPSHOT" pom.xml

        - name: Configure Git
          run: |
            git config --global user.name 'sudhirkilani1431987'
            git config --global user.email 'sudhir.kilani1431987@gmail.com' 
        - name: Commit changes
          run: |
              git add .
              git commit -m "Automated commit message"
        - name: Push changes
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          run: |
                git push origin main      

        - name: Pause for debugging
          run: sleep 300 
            

        
               
            
                        
                    
            
            
    

  
